[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "service_health_checker"
version = "0.1.0"
dependencies = [
    "typer",
    "typing_extensions",
    "requests",
    "pyyaml"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "requests-mock>1.12"
]

[project.scripts]
healthcheck = "service_health_checker.cli:app"
